version: '3'

services:
  bentley_ottmann-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/bentley_ottmann-cpython:7.3.0
    volumes:
      - ./bentley_ottmann:/opt/bentley_ottmann/bentley_ottmann
      - ./pyproject.toml:/opt/bentley_ottmann/pyproject.toml
      - ./README.md:/opt/bentley_ottmann/README.md
      - ./setup.py:/opt/bentley_ottmann/setup.py
      - ./tests:/opt/bentley_ottmann/tests
    entrypoint: pytest
